import { Link } from "react-router-dom";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

export default function Terms() {
  return (
    <div className="min-h-dvh bg-char-950">
      <SiteHeader />
      <div className="mx-auto max-w-3xl px-4 py-12 text-gray-300">
        <Link to="/" className="text-sm text-ember-400 hover:underline">
          ← Back home
        </Link>
      <h1 className="mt-4 font-display text-3xl font-bold text-white">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: June 28, 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-white">1. Acceptance of these Terms</h2>
          <p className="mt-2">
            By creating an account, upgrading to a paid plan, or otherwise using GiantBiteAI (the
            "Service"), you agree to these Terms of Service and our{" "}
            <a href="/privacy" className="text-ember-400 hover:underline">Privacy Policy</a>. If you
            don't agree, please don't use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">2. What GiantBiteAI is</h2>
          <p className="mt-2">
            GiantBiteAI provides AI-generated recipes, meal plans, nutrition estimates, and cooking
            guidance based on input you provide (text, photos, or pantry items). It is a free tier plus
            optional paid subscriptions (Regular and Pro). The Service does not require a user account —
            your plan tier and saved data live in your browser's local storage unless stated otherwise.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">3. Food safety &amp; health disclaimer — please read</h2>
          <p className="mt-2">
            Recipes, ingredient substitutions, nutrition estimates, and cooking guidance are generated by
            an AI model and <strong>may contain errors</strong> — including missed allergens, incorrect
            quantities, unsafe cooking temperatures/times, or inaccurate nutrition figures. GiantBiteAI is
            not a substitute for your own judgment, a doctor, or a registered dietitian.
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Always personally check every ingredient against your own allergies, intolerances, and dietary restrictions before cooking or eating.</li>
            <li>Nutrition values are AI estimates, not lab-verified label data — don't rely on them for medical dosing (e.g. diabetes, weight-related medical conditions) without your own verification.</li>
            <li>Follow safe food-handling and minimum cooking temperatures from a trusted source (e.g. your local food safety authority) regardless of what a recipe states.</li>
          </ul>
          <p className="mt-2">
            You use any recipe, substitution, or nutrition estimate at your own risk and discretion.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">4. Subscriptions &amp; billing</h2>
          <p className="mt-2">
            Regular and Pro are recurring monthly subscriptions billed through Stripe. You can cancel any
            time; cancellation takes effect at the end of the current billing period and you keep paid
            access until then. We don't offer prorated refunds for partial months except where required by
            law or at our discretion for billing errors. Prices may change with advance notice.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">5. Acceptable use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Use the Service for anything illegal, or to generate content that's abusive, harassing, or harmful to others.</li>
            <li>Attempt to bypass usage limits, paywalls, or rate limits, or scrape/resell the Service's output at scale.</li>
            <li>Reverse-engineer, decompile, or attempt to extract the underlying technology powering the Service.</li>
            <li>Use the Service to harm minors, or in any way that violates applicable law.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">6. Your content</h2>
          <p className="mt-2">
            You retain ownership of anything you input (pantry items, recipe text, photos). You grant us a
            limited license to process that input solely to generate your AI responses. We don't sell your
            inputs to third parties.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">7. Disclaimer of warranties</h2>
          <p className="mt-2">
            The Service is provided "as is" and "as available," without warranties of any kind, express or
            implied, including accuracy, fitness for a particular purpose, or uninterrupted availability.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">8. Limitation of liability</h2>
          <p className="mt-2">
            To the maximum extent permitted by law, GiantBiteAI and its operators are not liable for any
            indirect, incidental, or consequential damages — including any health, allergic-reaction, or
            financial outcome arising from reliance on AI-generated recipes, nutrition data, or cooking
            guidance. Our total liability for any claim is limited to the amount you paid us in the 3
            months before the claim arose.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">9. Termination</h2>
          <p className="mt-2">
            We may suspend or terminate access for violating these Terms. You may stop using the Service
            at any time; since most data is stored locally in your browser, clearing your browser data
            effectively deletes your saved recipes, plans, and tier status on that device.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">10. Changes to these Terms</h2>
          <p className="mt-2">
            We may update these Terms from time to time. Continuing to use the Service after an update
            means you accept the revised Terms. Material changes will be reflected by the "Last updated"
            date above.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">11. Governing law</h2>
          <p className="mt-2">These Terms are governed by the laws of the Province of Ontario, Canada.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">12. Contact</h2>
          <p className="mt-2">
            Questions about these Terms? Email <a href="mailto:hunter82kh@gmail.com" className="text-ember-400 hover:underline">hunter82kh@gmail.com</a>.
          </p>
        </section>
      </div>
      </div>
      <SiteFooter />
    </div>
  );
}
